/*
Main File
Compilers Lab Assignment 3
Manad Mishra
Roll No: 16CS30019
*/

#include <stdio.h>
#include <string.h>


int main(int argc,char *argv[]) {
	int token;
	while (token = yylex()) {
		switch (token) {
			case AUTO:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case ENUM:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case RESTRICT:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case UNSIGNED:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case BREAK:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case EXTERN:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case RETURN:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case VOID:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case CASE:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case FLOAT:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case SHORT:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case VOLATILE:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case CHAR:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case FOR:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case SIGNED:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case WHILE:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case CONST:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case GOTO:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case SIZEOF:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case _BOOL:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case CONTINUE:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case IF:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case STATIC:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case _COMPLEX:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case DEFAULT:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case INLINE:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case STRUCT:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case _IMAGINARY:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case DO:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case INT:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case SWITCH:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case DOUBLE:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case LONG:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case TYPEDEF:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case ELSE:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case REGISTER:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case UNION:		printf("<KEYWORD, %d, %s>\n", token, yytext); 
				break;
			case IDENTIFIER:		printf("<IDENTIFIER, %d, %s>\n", token, yytext); 
				break;
			case INTEGER_CONSTANT:		printf("<INTEGER_CONSTANT, %d, %s>\n", token, yytext); 
				break;
			case FLOATING_CONSTANT:		printf("<FLOATING_CONSTANT, %d, %s>\n", token, yytext); 
				break;
			case CHARACTER_CONSTANT:		printf("<CHARACTER_CONSTANT, %d, %s>\n", token, yytext); 
				break;
			case STRING_LITERAL:		printf("<STRING_LITERAL, %d, %s>\n", token, yytext); 
				break;
			case SQ_BRACKET_OPEN: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case SQ_BRACKET_CLOSE: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case RO_BRACKET_OPEN: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case RO_BRACKET_CLOSE: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case CUR_BRACKET_OPEN: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case CUR_BRACKET_CLOSE: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case DOT: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case ACC: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case INC: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case DEC: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case AMP: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case MUL: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case ADD: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case SUB: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case NEG: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case EXCLAIM: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case DIV: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case MODULO: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case SHIFT_L: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case SHIFT_R: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case BIT_SHIFT_L: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case BIT_SHIFT_R: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case LTE: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case GTE: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case EQ: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case NEQ: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case AND: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case OR: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case QUESTION: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case COLON: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case SEMICOLON: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case DOTS: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case ASSIGN: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case STAR_EQ: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case DIV_EQ: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case MOD_EQ: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case PLUS_EQ: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case MINUS_EQ: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case SHIFT_LEQ: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case SHIFT_REQ: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case BIN_AND_EQ: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case BIN_XOR_EQ: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case BIN_OR_EQ: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case COMMA: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case HASH: printf("<PUNCTUATION, %d, %s>\n", token, yytext);
				break;
			case SINGLE_LINE_COMMENT:		printf("<SINGLE_LINE_COMMENT, %d, %s>\n", token, yytext); 
				break;
			case MULTI_LINE_COMMENT:		printf("<MULTI_LINE_COMMENT, %d, %s>\n", token, yytext); 
				break;
		}
	}
	return 0;
}